# Generated by Django 3.2.15 on 2023-11-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_profile_geslacht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('DISABLED', 'Disabled'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=50),
        ),
    ]
