# Generated by Django 3.2.15 on 2023-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='geslacht',
            field=models.CharField(blank=True, choices=[('VROUW', 'Vrouw'), ('MAN', 'Man'), ('ANDERS', 'Anders')], max_length=50),
        ),
    ]
