# Generated by Django 3.2.15 on 2023-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_auto_20231128_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='geslacht',
            field=models.CharField(blank=True, choices=[('ANDERS', 'Anders'), ('MAN', 'Man'), ('VROUW', 'Vrouw')], max_length=50),
        ),
    ]
