# Generated by Django 3.2.15 on 2023-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_auto_20231128_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='geslacht',
            field=models.CharField(blank=True, choices=[('MAN', 'Man'), ('VROUW', 'Vrouw'), ('ANDERS', 'Anders')], max_length=50),
        ),
    ]
